language: node_js
sudo: required
services:
  - docker

before_install:
  - docker build -t docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true docker-react npm run test

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "sa-east-1"
  app: "docker-test"
  env: "DockerTest-env-1"
  bucket_name: "elasticbeanstalk-sa-east-1-303511236901"
  bucket_path: "docker-test"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
branches:
  only:
  - master